// <auto-generated />
using System;
using GorbushkaBot.AppDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GorbushkaBot.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250220230218_CreateFieldUserName")]
    partial class CreateFieldUserName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GorbushkaBot.Model.PinnedMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<int>("MessageId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("pinned_message", (string)null);
                });

            modelBuilder.Entity("GorbushkaBot.Model.UserAccept", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FacePhoto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Fio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FolderUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PassportIssueDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PassportIssueDateEnd")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PassportPhotos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PavilionNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PavilionPhotos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PropiskaPhoto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegistrationAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RentalContract")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserNameTg")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("user_accepts", (string)null);
                });

            modelBuilder.Entity("GorbushkaBot.Model.UserApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FacePhoto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Fio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FolderUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PassportIssueDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PassportIssueDateEnd")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PassportPhotos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PavilionNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PavilionPhotos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PropiskaPhoto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegistrationAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RentalContract")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserNameTg")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("user_applications", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
